name: test_expenses
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  cloud_firestore: ^3.1.11
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.12
  flutter_bloc: ^8.0.1
  uuid: ^3.0.6
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.0
  responsive_sizer: ^3.0.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4

flutter:

  uses-material-design: true

